# Generated by Django 5.2.17 on 2026-09-12 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendar_rules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jira_key', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('source', models.CharField(choices=[('jira', 'Jira'), ('email', 'Email')], default='jira', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4')], max_length=2)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('paused_minutes', models.PositiveIntegerField(default=0)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='calendar_rules.country')),
            ],
        ),
        migrations.CreateModel(
            name='ClockEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_from', models.CharField(max_length=50)),
                ('status_to', models.CharField(max_length=50)),
                ('at', models.DateTimeField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clock_events', to='tickets.ticket')),
            ],
            options={
                'ordering': ['at'],
            },
        ),
    ]
